[project]
name = "snowflake-keypair-helper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
 "snowflake-connector-python>=3.17.4",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
